brew "cocoapods"
brew "git"
brew "imagemagick"
brew "libpq"
brew "mas"
brew "mise"
brew "mole"
brew "sqlite", link: true
brew "stow"
brew "tcping"
brew "tree"
brew "watch"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "alt-tab"
cask "android-studio"
cask "betterdisplay"
cask "dbeaver-community"
cask "font-fira-code-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "godot"
cask "google-chrome"
cask "google-drive"
cask "lark"
cask "logi-options+"
cask "microsoft-teams"
cask "obsidian"
cask "orbstack"
cask "shottr"
cask "spotify"
cask "zen"
mas "LINE", id: 539883307
mas "PDFgear 2", id: 6469021132
mas "Telegram 2", id: 747648890
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
