tap "homebrew/bundle"
tap "jandedobbeleer/oh-my-posh"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "atuin"
brew "openssl@3"
brew "awscli"
brew "bat"
brew "carapace"
brew "direnv"
brew "docker"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "git"
brew "gitleaks"
brew "go"
brew "goose"
brew "jq"
brew "just"
brew "kubernetes-cli"
brew "kubectx"
brew "lazygit"
brew "mas"
brew "neovim"
brew "node"
brew "ollama"
brew "pre-commit"
brew "ripgrep"
brew "ruff"
brew "rust"
brew "shellcheck"
brew "sqlc"
brew "stow"
brew "terraform"
brew "tldr"
brew "tmux"
brew "tree"
brew "uv"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "qmk/qmk/qmk"
cask "alt-tab"
cask "ghostty"
cask "google-drive"
cask "hiddenbar"
cask "hyperkey"
cask "orbstack"
cask "qmk-toolbox"
cask "raycast"
cask "whatsapp"
cask "zen-browser"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PDFgear", id: 6469021132
mas "Xnip", id: 1221250572
