vim.pack.add { 'https://github.com/romus204/tree-sitter-manager.nvim' }

require('tree-sitter-manager').setup {
    auto_install = true,
    ensure_installed = {
        'bash',
        'c',
        'cpp',
        'css',
        'cue',
        'diff',
        'dockerfile',
        'gitcommit',
        'go',
        'gomod',
        'gosum',
        'gowork',
        'helm',
        'html',
        'javascript',
        'jq',
        'json',
        'jsonnet',
        'just',
        'lua',
        'luadoc',
        'markdown',
        'markdown_inline',
        'nu',
        'python',
        'query',
        'regex',
        'scss',
        'sql',
        'starlark',
        'terraform',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'vimdoc',
        'yaml',
        'zig',
    },
}
