#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export CLOUDSDK_CONFIG="$HOME/.gcloud"
export GOPATH=~/go
export KUBE_EDITOR=vim
export PATH=$PATH:$GOPATH/bin
export TERM=xterm-256color
export GOOGLE_APPLICATION_CREDENTIALS="/Users/po.locp/.gcloud/application_default_credentials.json"
export POETRY_VIRTUALENVS_IN_PROJECT=true

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

