#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# up arrow for substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Autocomplete
autoload -U compinit; compinit

source <(kubectl completion zsh)
source <(docker completion zsh)
source <(helm completion zsh)

# Functions
pwdcopy() {
    command pwd "$@" | tr -d '\n' | pbcopy
    command pwd "$@"
}

# Aliases for Tool Replacements
alias cd="z"
alias pwd="pwdcopy"
alias ls="eza --group-directories-first -a --icons"
alias vi="nvim"
alias vim="nvim"
alias cat="bat -p"

# Shortened Commands
alias c="code ."
alias cafe="caffeinate -d"
alias cls="clear"
alias ff="fzf --preview='cat {}' | pbcopy"
alias k="kubectl"
alias lg="lazygit"
alias o="open ."
alias p="poetry"
alias pa="poetry add"
alias tf="terraform"

# Command Updates & Rebuilds
alias brewup="zsh ~/.config/homebrew/brewup.sh"
alias nixup="nix flake update --flake $NIX_HOME && darwin-rebuild switch --flake $NIX_HOME && cz add $NIX_HOME"

# URL Copying
alias url="tmux capture-pane -J -p | grep -oE '(https?):\/\/.*[^>]' | fzf-tmux -d20 --multi --bind alt-a:select-all,alt-d:deselect-all | xargs open"

# Configuration Reloads
alias st="tmux source-file ${XDG_CONFIG_HOME:-$HOME}/tmux/tmux.conf"
alias sz="source ${ZDOTDIR:-$HOME}/.zshrc"

# Editor & Formatter
alias pretty="npx prettier-init"
alias cz="chezmoi"
alias setenv='echo '\''{ "venvPath": ".", "venv": ".venv" }'\'' > pyrightconfig.json'

# Interactive sessions
source <(fzf --zsh)
eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/config.yaml)"
eval "$(zoxide init zsh)"
eval "$(atuin init zsh)"

