# yaml-language-server: $schema=https://raw.githubusercontent.com/derailed/k9s/refs/heads/master/internal/config/json/schemas/k9s.json
k9s:
  noExitOnCtrlC: true
  ui:
    skin: catppuccin-mocha-transparent
  imageScans:
    enable: false
  logger:
    tail: 500
    buffer: 5000
